# Generated by Django 2.0.5 on 2018-10-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=1000)),
                ('country', models.CharField(choices=[('Option 1', 'United States'), ('Option 2', 'India')], max_length=50)),
                ('zipcode', models.IntegerField()),
                ('data', models.CharField(max_length=2000)),
            ],
        ),
    ]
