# Generated by Django 2.0.5 on 2018-10-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='country',
            field=models.CharField(choices=[('United States', 'United States'), ('India', 'India')], max_length=50),
        ),
    ]
